### PR TITLE
Removed emoji padding

### PR DESCRIPTION
**Pull request by awwong1**
fixes emoji selector padding causing all of the right most icons to be unselectable.

### CODE REVIEW

**Comment by awwong1** [comment]
https://github.com/aflashyrhetoric/NightMessenger/issues/3

screen shot 2017-12-25 at 7 54 53 pm

**Comment by aflashyrhetoric** [comment]
Ahhhh, thank you for the PR! I think I may tweak the selectors before merging but thank you for taking the initiative.

I don't recall at the moment, but I think the padding was added in the first place because it adds a pleasant little cushion around emojis that are sent as standalone messages. I'll double-check soon and merge. 👍

**Comment by awwong1** [comment]
I recall reading that you wanted to do a rewrite.

Consider this an interim patch on a hack. I think it looks fine without the
padding, honestly I'd rather be able to select emojis. Happy holidays!

**Comment by aflashyrhetoric** [comment]
Ah, I hear you. In that case, I will merge now and try to deploy the fix later tonight. Thanks again :bowtie:

**Pull request merged**
